// <auto-generated />
namespace Casgem_PortfolioCodeFirstProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_continue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_continue));
        
        string IMigrationMetadata.Id
        {
            get { return "202307161127434_mig_continue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
